// placement-bank.js — Banco v2 del placement de nivel.
// ESTRUCTURA:
//   barco (ship) = tema(s) de un nivel.  8 barcos en escalera de dificultad.
//   contenedor (container) = 'conoce' (vocab) | 'entiende' | 'produce'.
//   dificultad (tier) = 'facil' | 'media' | 'dificil'.
//   18 preguntas por barco = 3 contenedores × 3 dificultades × 2.
// El motor sirve preguntas 1 a 1 caminando la matriz; NO entrega contenedores completos.
// Lo consumen placement-test.html (motor) y dashboard-pt.html (editor).
//
// Mini-games con las mejoras ya aplicadas:
//   matching      → pairs[{left,right}] + distractors[]  (respuestas falsas extra, sin par)
//   unscramble    → words[] (incluye distractores que NO se usan) + answer + acceptedAnswers[] + spanishPrompt + targetLabel
//   audioQuestion → opciones en ESPAÑOL (mide comprensión real, no eco fonético)
//   dialogueFill  → dialogue[{speaker,line}] con line:null en el turno del alumno + 3er turno de reacción

window.PERIPLO_BANK = {
  ships: [
    {
      id: 'ship1', n: 1, label: 'Modal Verbs', level: 'B1', module: 'B1 Foundation', week: 1,
      entry: 'no_sabe', entryTier: 'facil',
      grammar: 'Modal Verbs — can · must · will · might · should',
      vocab: 'VP1 Daily Routine & Work · NP1 Modern Nomad',
      questions: [
        // ── CONOCE (vocab VP1 / NP1) ──────────────────────────────────────────
        { id:'s1_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'Charger',right:'Cargador'},{left:'Wallet',right:'Cartera'},{left:'Keys',right:'Llaves'},{left:'Backpack',right:'Mochila'}],
          distractors:['Reloj','Cinturón'] },
        { id:'s1_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT a travel document?',
          options:['Passport','ID','Ticket','Charger'], answer:'Charger' },
        { id:'s1_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'You use it to charge your phone when there is no outlet. What is it?',
          options:['Power bank','Wallet','Notebook','Umbrella'], answer:'Power bank' },
        { id:'s1_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:"It's raining and I forgot my ___.", hint:'lo abres cuando llueve', answer:'umbrella' },
        { id:'s1_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word: is it an action (verb) or a thing (noun)?',
          pool:['take','send','buy','Laptop','Wallet','Keys'],
          buckets:[{label:'Verbo (acción)',correct:['take','send','buy']},{label:'Sustantivo (cosa)',correct:['Laptop','Wallet','Keys']}] },
        { id:'s1_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'Before I leave home, I always pick up my keys, my wallet, and my charger.',
          q:'What does the person pick up?',
          options:['Sus llaves, cartera y cargador','Su pasaporte y boleto','Su laptop y audífonos','Su paraguas y mochila'],
          answer:'Sus llaves, cartera y cargador' },

        // ── ENTIENDE (modales — comprensión) ─────────────────────────────────
        { id:'s1_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'I have my laptop and a good signal, so I ___ work from anywhere.',
          options:['can','must','should','might'], answer:'can' },
        { id:'s1_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"You mustn\'t take photos here" means it is NOT allowed.', answer:true },
        { id:'s1_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'You should charge your power bank before you leave.',
          q:'What is the speaker doing?',
          options:['Dando un consejo','Dando una orden','Pidiendo permiso','Haciendo una predicción'],
          answer:'Dando un consejo' },
        { id:'s1_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each modal with its function:',
          pairs:[{left:'Can',right:'Habilidad / permiso'},{left:'Must',right:'Obligación'},{left:'Should',right:'Consejo'},{left:'Might',right:'Posibilidad'}],
          distractors:['Pasado terminado','Deseo imposible'] },
        { id:'s1_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:"I can't find my passport!"},{speaker:'B',line:null},{speaker:'A',line:"Good idea, I'll check there."}],
          options:['You should look in your backpack.','You must look in your backpack.','You might look in your backpack.','You will look in your backpack.'],
          answer:'You should look in your backpack.' },
        { id:'s1_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'It is only a possibility, not a sure plan. Which sentence shows that?',
          options:['I might visit my family this weekend.','I must visit my family this weekend.','I can visit my family this weekend.','I will visit my family this weekend.'],
          answer:'I might visit my family this weekend.' },

        // ── PRODUCE (modales — producción) ───────────────────────────────────
        { id:'s1_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:"I'm not sure about my plans. I ___ visit my family this weekend.",
          hint:'posibilidad (no es seguro)', answer:'might' },
        { id:'s1_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'¿Dónde puedo comprar un boleto?', targetLabel:'Arma la PREGUNTA (?)',
          words:['Where','can','I','buy','a','ticket','do','to'],
          answer:'Where can I buy a ticket?', acceptedAnswers:['where can i buy a ticket'] },
        { id:'s1_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'There is no signal here, so I ___ send the email.',
          hint:'no puedo (negativo de can)', answer:"can't", accept:['cannot','can not'] },
        { id:'s1_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'No deberías comprar ese adaptador.', targetLabel:'Arma la oración en NEGATIVO (−)',
          words:['You',"shouldn't",'buy','that','adapter','should','not'],
          answer:"You shouldn't buy that adapter", acceptedAnswers:['you shouldnt buy that adapter','you should not buy that adapter'] },
        { id:'s1_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'¿Dónde puedo comprar un boleto?', answer:'Where can I buy a ticket?', acceptedAnswers:['where can i buy a ticket'] },
        { id:'s1_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['I can help you tomorrow.','I can to help you tomorrow.',"She won't buy a new charger.",'He should drives carefully.'],
          answers:['I can help you tomorrow.',"She won't buy a new charger."] },
      ],
    },

    // ── Barcos 2-8 — esqueletos (se llenan tras validar el Barco 1) ──────────
    { id:'ship2', n:2, label:'B1', level:'B1', module:'B1 Foundation', week:3,
      grammar:'Present Simple · Present Continuous · Future Going To',
      vocab:'VP2-4 · NP2-4 — Hungry Traveler / Travel & Places / Emotions & Mind',
      questions:[
        // CONOCE (vocab NP2-4)
        { id:'s2_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'Desk',right:'Escritorio'},{left:'Meeting',right:'Junta'},{left:'Schedule',right:'Horario'},{left:'Colleague',right:'Colega'}],
          distractors:['Almohada','Cobija'] },
        { id:'s2_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT a meal?', options:['Breakfast','Lunch','Dinner','Desk'], answer:'Desk' },
        { id:'s2_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'You sit on it at the office. What is it?', options:['Chair','Stove','Highway','Ticket'], answer:'Chair' },
        { id:'s2_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:"There's a lot of ___ on the highway this morning.", hint:'carros que no avanzan', answer:'traffic' },
        { id:'s2_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word: action (verb) or thing (noun)?',
          pool:['cook','eat','drive','Office','Boss','Ticket'],
          buckets:[{label:'Verbo (acción)',correct:['cook','eat','drive']},{label:'Sustantivo (cosa)',correct:['Office','Boss','Ticket']}] },
        { id:'s2_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:"I usually take the subway to work, but today there's a delay, so I'm walking.",
          q:'How is the person getting to work today?',
          options:['Caminando','En metro','En carro','En taxi'], answer:'Caminando' },
        // ENTIENDE (present simple / continuous / going to)
        { id:'s2_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'My sister ___ breakfast every morning.', options:['cooks','is cooking','cook','is cook'], answer:'cooks' },
        { id:'s2_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"She doesn\'t eat dessert" is the correct negative form.', answer:true },
        { id:'s2_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'Look! The boss is talking to a client right now.',
          q:'When is the boss talking to the client?',
          options:['Ahora mismo','Todos los días','Ayer','Nunca'], answer:'Ahora mismo' },
        { id:'s2_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each tense with its use:',
          pairs:[{left:'Present Simple',right:'Rutina / hábito'},{left:'Present Continuous',right:'Acción ahora mismo'},{left:'Going to',right:'Plan futuro'}],
          distractors:['Pasado terminado','Orden directa'] },
        { id:'s2_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'Where is your boss?'},{speaker:'B',line:null},{speaker:'A',line:"Okay, I'll wait then."}],
          options:['He is having a meeting.','He having a meeting.','He is have a meeting.','He have a meeting.'],
          answer:'He is having a meeting.' },
        { id:'s2_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'Which sentence is a future plan decided before now?',
          options:["I'm going to take the subway downtown.",'I take the subway downtown.','I take the subway right now.','I am subway downtown.'],
          answer:"I'm going to take the subway downtown." },
        // PRODUCE
        { id:'s2_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'___ your brother cook dinner on weekends?', hint:'auxiliar para 3ra persona', answer:'Does' },
        { id:'s2_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'¿Qué vas a ordenar?', targetLabel:'Arma la PREGUNTA (?)',
          words:['What','are','you','going','to','order','do','is'],
          answer:'What are you going to order?', acceptedAnswers:['what are you going to order'] },
        { id:'s2_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'He is ___ the report now. (write)', hint:'verbo + -ing', answer:'writing' },
        { id:'s2_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'¿Por qué se va temprano el empleado?', targetLabel:'Arma la PREGUNTA (?)',
          words:['Why','is','the','employee','leaving','early','does','do'],
          answer:'Why is the employee leaving early?', acceptedAnswers:['why is the employee leaving early'] },
        { id:'s2_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'¿Dónde almuerza tu hermana?', answer:'Where does your sister eat lunch?', acceptedAnswers:['where does your sister eat lunch','where does your sister have lunch'] },
        { id:'s2_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['She cooks dinner every night.',"He don't eat breakfast.",'They read the menu carefully.','My friend speak with the chef.'],
          answers:['She cooks dinner every night.','They read the menu carefully.'] },
      ] },
    { id:'ship3', n:3, label:'B2', level:'B2', module:'B2 Structures', week:2,
      grammar:'Prepositions · Object Pronouns · Quantifiers + There is/are · Possessives (vocab-heavy)',
      vocab:'VP5-8 · NP5-8 — Strategy / People / Society / Money',
      questions:[
        // CONOCE (vocab NP5-8)
        { id:'s3_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'Revenue',right:'Ingresos'},{left:'Budget',right:'Presupuesto'},{left:'Contract',right:'Contrato'},{left:'Loss',right:'Pérdida'}],
          distractors:['Regalo','Fábrica'] },
        { id:'s3_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT about money?', options:['Profit','Budget','Tax','Jacket'], answer:'Jacket' },
        { id:'s3_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'The money a company earns from selling. What is it?', options:['Revenue','Outfit','Crowd','Route'], answer:'Revenue' },
        { id:'s3_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:'She signed the ___ before starting the new job.', hint:'documento legal del trabajo', answer:'contract' },
        { id:'s3_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word: action (verb) or thing (noun)?',
          pool:['invest','earn','negotiate','Profit','Budget','Stock'],
          buckets:[{label:'Verbo (acción)',correct:['invest','earn','negotiate']},{label:'Sustantivo (cosa)',correct:['Profit','Budget','Stock']}] },
        { id:'s3_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'Our company made a big profit this year, but we have a tight budget for next year.',
          q:'What did the company have this year?',
          options:['Una gran ganancia','Una gran pérdida','Un presupuesto enorme','Una deuda'], answer:'Una gran ganancia' },
        // ENTIENDE (prepositions / pronouns / quantifiers / possessives)
        { id:'s3_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'Your boots are ___ the suitcase.', options:['in','on','at','to'], answer:'in' },
        { id:'s3_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"There is three results" is correct.', answer:false },
        { id:'s3_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'This account is theirs, not ours.', q:'Whose account is it?',
          options:['De ellos','Nuestra','Mía','De él'], answer:'De ellos' },
        { id:'s3_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each subject pronoun with its object form:',
          pairs:[{left:'I',right:'me'},{left:'he',right:'him'},{left:'she',right:'her'},{left:'we',right:'us'}],
          distractors:['my','their'] },
        { id:'s3_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'Do you know Mr. López?'},{speaker:'B',line:null},{speaker:'A',line:'Great, can you introduce me?'}],
          options:['Yes, I know him.','Yes, I know he.','Yes, I know his.','Yes, I him know.'],
          answer:'Yes, I know him.' },
        { id:'s3_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'How ___ people came to the protest?', options:['many','much','a little','any'], answer:'many' },
        // PRODUCE
        { id:'s3_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'We walked ___ the market to find a souvenir.', hint:'a través de', answer:'through' },
        { id:'s3_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'La llamo todos los días.', targetLabel:'Arma la AFIRMACIÓN (+)',
          words:['I','call','her','every','day','she','to'],
          answer:'I call her every day', acceptedAnswers:['i call her every day'] },
        { id:'s3_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'This budget is ___, not yours.', hint:'pronombre posesivo (de mí)', answer:'mine' },
        { id:'s3_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'¿Hay alguna investigación sobre esto?', targetLabel:'Arma la PREGUNTA (?)',
          words:['Is','there','any','research','on','this','some','are'],
          answer:'Is there any research on this?', acceptedAnswers:['is there any research on this'] },
        { id:'s3_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'Depende del clima.', answer:'It depends on the weather.', acceptedAnswers:['it depends on the weather'] },
        { id:'s3_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['She is good at sports.','She is good in sports.',"I'm interested in art.","I'm interested on art."],
          answers:['She is good at sports.',"I'm interested in art."] },
      ] },
    { id:'ship4', n:4, label:'B1 gram + B2 vocab', level:'B2', module:'B2 Structures', week:4,
      entry:'se_defiende', entryTier:'facil',
      grammar:'Gramática B1 aplicada con el vocab/estructuras-léxicas de B2',
      vocab:'VP5-8 · NP5-8 — Corporate & Economy (más exigente)',
      questions:[
        // CONOCE (vocab B2 más exigente)
        { id:'s4_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each adjective with its meaning:',
          pairs:[{left:'Expensive',right:'Caro'},{left:'Clean',right:'Limpio'},{left:'Nervous',right:'Nervioso'},{left:'Tired',right:'Cansado'}],
          distractors:['Rápido','Vacío'] },
        { id:'s4_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which adjective does NOT describe an emotion?', options:['Happy','Nervous','Proud','Expensive'], answer:'Expensive' },
        { id:'s4_con_m1', container:'conoce', tier:'media', type:'categorySort',
          q:'Sort each adjective: does it describe a thing, or an emotion?',
          pool:['Expensive','Heavy','Clean','Nervous','Excited','Proud'],
          buckets:[{label:'Describe un objeto / cosa',correct:['Expensive','Heavy','Clean']},{label:'Describe una emoción',correct:['Nervous','Excited','Proud']}] },
        { id:'s4_con_m2', container:'conoce', tier:'media', type:'matching',
          q:'Match each adjective with its meaning:',
          pairs:[{left:'Exhausted',right:'Agotado'},{left:'Crowded',right:'Concurrido'},{left:'Outgoing',right:'Extrovertido'},{left:'Hardworking',right:'Trabajador'}],
          distractors:['Tímido','Peligroso'] },
        { id:'s4_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word: action (verb) or thing (noun)?',
          pool:['promote','resign','hire','Stock','Asset','Debt'],
          buckets:[{label:'Verbo (acción)',correct:['promote','resign','hire']},{label:'Sustantivo (cosa)',correct:['Stock','Asset','Debt']}] },
        { id:'s4_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'After the merger, many employees were worried about losing their jobs.',
          q:'Why were the employees worried?',
          options:['Por perder su trabajo','Por un aumento de sueldo','Por las vacaciones','Por la comida'], answer:'Por perder su trabajo' },
        // ENTIENDE (gramática B1 con vocab B2)
        { id:'s4_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'The board ___ a new strategy every quarter.', options:['reviews','is review','review','are review'], answer:'reviews' },
        { id:'s4_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"The shareholders are meeting right now" uses the present continuous correctly.', answer:true },
        { id:'s4_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'The CEO is going to announce the merger tomorrow morning.',
          q:'When is the CEO going to announce the merger?',
          options:['Mañana en la mañana','Ahora mismo','La semana pasada','Nunca'], answer:'Mañana en la mañana' },
        { id:'s4_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each tense with its business use:',
          pairs:[{left:'Present Simple',right:'Política de la empresa'},{left:'Present Continuous',right:'Negociación en curso'},{left:'Going to',right:'Plan ya anunciado'}],
          distractors:['Contrato firmado ayer','Deuda del pasado'] },
        { id:'s4_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'Where is the manager?'},{speaker:'B',line:null},{speaker:'A',line:"Okay, I'll email her later."}],
          options:['She is negotiating a contract.','She negotiating a contract.','She is negotiate a contract.','She negotiate a contract.'],
          answer:'She is negotiating a contract.' },
        { id:'s4_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'Which sentence is an announced plan?',
          options:['We are going to invest in new markets.','We invest in new markets.','We are investing right now.','We invested last year.'],
          answer:'We are going to invest in new markets.' },
        // PRODUCE
        { id:'s4_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'___ the company hire new employees this year?', hint:'auxiliar para 3ra persona', answer:'Does' },
        { id:'s4_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'¿Qué van a producir el próximo año?', targetLabel:'Arma la PREGUNTA (?)',
          words:['What','are','they','going','to','produce','next','year','do'],
          answer:'What are they going to produce next year?', acceptedAnswers:['what are they going to produce next year'] },
        { id:'s4_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'The accountant is ___ the budget right now. (review)', hint:'verbo + -ing', answer:'reviewing' },
        { id:'s4_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'La empresa no invierte en acciones.', targetLabel:'Arma la oración en NEGATIVO (−)',
          words:['The','company',"doesn't",'invest','in','stocks','not','does'],
          answer:"The company doesn't invest in stocks", acceptedAnswers:['the company doesnt invest in stocks','the company does not invest in stocks'] },
        { id:'s4_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'¿Dónde se reúnen los accionistas cada año?', answer:'Where do the shareholders meet every year?', acceptedAnswers:['where do the shareholders meet every year','where do shareholders meet every year'] },
        { id:'s4_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['The board approves the budget.','The board approve the budget.','They are negotiating the contract.','They negotiating the contract.'],
          answers:['The board approves the budget.','They are negotiating the contract.'] },
      ] },
    { id:'ship5', n:5, label:'B1/B2 + Past Irregular', level:'A1', module:'A1 Foundation', week:1,
      entry:'falla_hablar', entryTier:'media',
      grammar:'Integración B1/B2 + Past Simple (verbos irregulares)',
      vocab:'Irregular verbs · NP1 Adv Success & Failure',
      questions:[
        // CONOCE (formas irregulares + NP1 Adv)
        { id:'s5_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each verb with its Past Simple form:',
          pairs:[{left:'buy',right:'bought'},{left:'eat',right:'ate'},{left:'drive',right:'drove'},{left:'find',right:'found'}],
          distractors:['eated','finded'] },
        { id:'s5_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which past form is INCORRECT?', options:['bought','caught','finded','drank'], answer:'finded' },
        { id:'s5_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'The Past Simple of "buy" is...', options:['bought','buyed','buy','buying'], answer:'bought' },
        { id:'s5_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:'Yesterday I ___ a new laptop. (buy)', hint:'pasado irregular de buy', answer:'bought' },
        { id:'s5_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each past form: irregular or regular (-ed)?',
          pool:['ate','drove','drank','played','worked','cooked'],
          buckets:[{label:'Pasado irregular',correct:['ate','drove','drank']},{label:'Pasado regular (-ed)',correct:['played','worked','cooked']}] },
        { id:'s5_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'She drove to the office and bought a coffee before the meeting.',
          q:'What did she do before the meeting?',
          options:['Manejó y compró un café','Voló y comió','Corrió y durmió','Caminó y leyó'], answer:'Manejó y compró un café' },
        // ENTIENDE (past simple — comprensión)
        { id:'s5_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'Last year she ___ a major milestone.', options:['reached','reach','reaches','reaching'], answer:'reached' },
        { id:'s5_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"Did he bought a ticket?" is correct.', answer:false },
        { id:'s5_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:"He didn't catch the train, so he was late.", q:'What happened to him?',
          options:['No alcanzó el tren','Compró un boleto','Manejó al trabajo','Durmió tarde'], answer:'No alcanzó el tren' },
        { id:'s5_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each verb with its Past Simple form:',
          pairs:[{left:'come',right:'came'},{left:'find',right:'found'},{left:'drink',right:'drank'},{left:'fall',right:'fell'}],
          distractors:['comed','falled'] },
        { id:'s5_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'Why are you so tired?'},{speaker:'B',line:null},{speaker:'A',line:"Wow, that's a long drive!"}],
          options:['I drove for ten hours yesterday.','I drive for ten hours yesterday.','I driven for ten hours.','I was drive for ten hours.'],
          answer:'I drove for ten hours yesterday.' },
        { id:'s5_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'Which sentence is correct in the past?',
          options:['She bought a new phone last week.','She buyed a new phone last week.','She did bought a new phone.','She buy a new phone last week.'],
          answer:'She bought a new phone last week.' },
        // PRODUCE
        { id:'s5_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'After many obstacles, she finally ___ her goal. (reach)', hint:'pasado regular', answer:'reached' },
        { id:'s5_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'¿Cuándo empezaste tu trabajo?', targetLabel:'Arma la PREGUNTA (?)',
          words:['When','did','you','start','your','job','do','started'],
          answer:'When did you start your job?', acceptedAnswers:['when did you start your job'] },
        { id:'s5_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'He finally ___ a good solution. (find)', hint:'pasado irregular de find', answer:'found' },
        { id:'s5_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'Ella no compró el boleto.', targetLabel:'Arma la oración en NEGATIVO (−)',
          words:['She',"didn't",'buy','the','ticket','bought','not'],
          answer:"She didn't buy the ticket", acceptedAnswers:['she didnt buy the ticket','she did not buy the ticket'] },
        { id:'s5_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'¿Ella logró su meta?', answer:'Did she achieve her goal?', acceptedAnswers:['did she achieve her goal','did she reach her goal'] },
        { id:'s5_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:["She didn't finish the project.","She didn't finished the project.",'He bought a new car.','He buyed a new car.'],
          answers:["She didn't finish the project.",'He bought a new car.'] },
      ] },
    { id:'ship6', n:6, label:'A1 + Past & Participles', level:'A1', module:'A1 Foundation', week:4,
      entry:'faltan_detalles', entryTier:'media',
      grammar:'Past Simple/Continuous · Was going to · 2nd Conditional + participios',
      vocab:'NP1-4 Adv — Success / Truth / Media / Regrets',
      questions:[
        // CONOCE (vocab NP1-4 Adv)
        { id:'s6_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'achievement',right:'Logro'},{left:'setback',right:'Revés'},{left:'betrayal',right:'Traición'},{left:'regret',right:'Arrepentimiento'}],
          distractors:['Cosecha','Vecino'] },
        { id:'s6_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT about success or failure?', options:['achievement','milestone','breakthrough','algorithm'], answer:'algorithm' },
        { id:'s6_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'A big, important step forward in your life or career. What is it?', options:['milestone','setback','rumor','audience'], answer:'milestone' },
        { id:'s6_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:'After the scandal, the politician lost all his ___.', hint:'buena imagen pública', answer:'reputation' },
        { id:'s6_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word by its theme:',
          pool:['achievement','setback','breakthrough','deception','sincerity','betrayal'],
          buckets:[{label:'Success & Failure',correct:['achievement','setback','breakthrough']},{label:'Truth & Lies',correct:['deception','sincerity','betrayal']}] },
        { id:'s6_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'After years of setbacks, she finally had her big breakthrough.',
          q:'What finally happened to her?',
          options:['Tuvo un gran avance','Tuvo otro fracaso','Perdió su trabajo','Se rindió'], answer:'Tuvo un gran avance' },
        // ENTIENDE (past continuous / participles / 2nd conditional)
        { id:'s6_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'At 9 PM, millions ___ watching the premiere.', options:['were','was','are','is'], answer:'were' },
        { id:'s6_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'The past participle of "break" is "broken".', answer:true },
        { id:'s6_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'While she was writing the review, the news broke.', q:'What was she doing when the news broke?',
          options:['Escribía una reseña','Leía el periódico','Dormía','Manejaba'], answer:'Escribía una reseña' },
        { id:'s6_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each verb with its Past Participle:',
          pairs:[{left:'break',right:'broken'},{left:'write',right:'written'},{left:'eat',right:'eaten'},{left:'drive',right:'driven'}],
          distractors:['breaked','writed'] },
        { id:'s6_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'What were you doing when the movie started?'},{speaker:'B',line:null},{speaker:'A',line:'Haha, classic you!'}],
          options:['I was waiting in line.','I waiting in line.','I was wait in line.','I waited all time.'],
          answer:'I was waiting in line.' },
        { id:'s6_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'Which sentence uses the second conditional correctly?',
          options:['If I knew the truth, I would tell you.','If I know the truth, I would tell you.','If I would know, I tell you.','If I knew, I will tell you.'],
          answer:'If I knew the truth, I would tell you.' },
        // PRODUCE
        { id:'s6_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'While the critic ___ the review, the news broke. (write)', hint:'was + verbo-ing', answer:'was writing' },
        { id:'s6_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'Si yo fuera tú, confesaría.', targetLabel:'Arma la oración (2nd conditional)',
          words:['If','I','were','you','I','would','confess','was','will'],
          answer:'If I were you I would confess', acceptedAnswers:['if i were you i would confess'] },
        { id:'s6_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'She has ___ three reports this week. (write)', hint:'participio de write', answer:'written' },
        { id:'s6_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'¿Qué estabas viendo cuando pasó?', targetLabel:'Arma la PREGUNTA (?)',
          words:['What','were','you','watching','when','it','happened','was','did'],
          answer:'What were you watching when it happened?', acceptedAnswers:['what were you watching when it happened'] },
        { id:'s6_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'Los fans estaban esperando afuera toda la noche.', answer:'The fans were waiting outside all night.', acceptedAnswers:['the fans were waiting outside all night'] },
        { id:'s6_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['I was watching TV when she called.','I watching TV when she called.','If I had money, I would travel.','If I would have money, I would travel.'],
          answers:['I was watching TV when she called.','If I had money, I would travel.'] },
      ] },
    { id:'ship7', n:7, label:'A1 + A2', level:'A2', module:'A2 Structures', week:2,
      grammar:'A1 completo + Comparatives & Superlatives + Present Perfect Continuous',
      vocab:'NP5-8 Adv — Attraction / Ambition / Mystery / Society',
      questions:[
        // CONOCE (vocab NP5-8 Adv)
        { id:'s7_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'suspect',right:'Sospechoso'},{left:'witness',right:'Testigo'},{left:'motive',right:'Motivo'},{left:'evidence',right:'Evidencia'}],
          distractors:['Juez','Cárcel'] },
        { id:'s7_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT about crime or mystery?', options:['suspect','alibi','motive','chemistry'], answer:'chemistry' },
        { id:'s7_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'The reason someone commits a crime. What is it?', options:['motive','verdict','benchmark','phase'], answer:'motive' },
        { id:'s7_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:'The detective found an important ___ at the crime scene.', hint:'pista que ayuda a resolver el caso', answer:'clue' },
        { id:'s7_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word by its theme:',
          pool:['suspect','witness','alibi','benchmark','contender','rivalry'],
          buckets:[{label:'Mystery & Crime',correct:['suspect','witness','alibi']},{label:'Ambition & Competition',correct:['benchmark','contender','rivalry']}] },
        { id:'s7_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'The witness gave a clear testimony, but the suspect had a strong alibi.',
          q:'Who had a strong alibi?',
          options:['El sospechoso','El testigo','El detective','La víctima'], answer:'El sospechoso' },
        // ENTIENDE (comparatives / superlatives / PPC)
        { id:'s7_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'This contender is ___ than the others.', options:['stronger','more strong','strongest','more stronger'], answer:'stronger' },
        { id:'s7_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'"She has been working here for years" describes an action that started in the past and still continues.', answer:true },
        { id:'s7_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'Their strategy was better than ours, but ours was the cheapest.', q:'Whose strategy was cheaper?',
          options:['La nuestra','La de ellos','Ninguna','Ambas igual'], answer:'La nuestra' },
        { id:'s7_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each structure with its use:',
          pairs:[{left:'Comparative',right:'Compara DOS cosas (-er / more)'},{left:'Superlative',right:'El más de TODOS (the -est / most)'},{left:'Present Perfect Continuous',right:'Acción que sigue pasando (have been + -ing)'}],
          distractors:['Acción terminada ayer','Plan del futuro'] },
        { id:'s7_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'How long have you been studying English?'},{speaker:'B',line:null},{speaker:'A',line:"Wow, that's dedication!"}],
          options:["I've been studying for three years.",'I study for three years.',"I'm studying since three years.",'I been studying three years.'],
          answer:"I've been studying for three years." },
        { id:'s7_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'Which sentence is the correct superlative?',
          options:['She is the most ruthless competitor.','She is most ruthless competitor.','She is the ruthlessest competitor.','She is more ruthless of all.'],
          answer:'She is the most ruthless competitor.' },
        // PRODUCE
        { id:'s7_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:"This year's benchmark is ___ than last year's. (high)", hint:'comparativo de adjetivo corto', answer:'higher' },
        { id:'s7_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'Ella ha estado trabajando aquí por años.', targetLabel:'Arma la AFIRMACIÓN (+)',
          words:['She','has','been','working','here','for','years','since','is'],
          answer:'She has been working here for years', acceptedAnswers:['she has been working here for years'] },
        { id:'s7_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'It was the ___ negotiation of her career. (tough)', hint:'the + adjetivo + est', answer:'toughest' },
        { id:'s7_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'¿Cuánto tiempo has estado esperando?', targetLabel:'Arma la PREGUNTA (?)',
          words:['How','long','have','you','been','waiting','has','did'],
          answer:'How long have you been waiting?', acceptedAnswers:['how long have you been waiting'] },
        { id:'s7_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'Ella es más inteligente que su competidora.', answer:'She is smarter than her competitor.', acceptedAnswers:['she is smarter than her competitor','shes smarter than her competitor'] },
        { id:'s7_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['He is more ambitious than me.','He is more ambitiouser than me.','They have been waiting since noon.','They has been waiting since noon.'],
          answers:['He is more ambitious than me.','They have been waiting since noon.'] },
      ] },
    { id:'ship8', n:8, label:'P1 (sin Passive)', level:'P1', module:'P1 Structures', week:2,
      grammar:'Present/Past Perfect · 3rd & Mixed Conditionals · Past Conditionals',
      vocab:'NP Pro — Law & Politics / Finance / Science',
      questions:[
        // CONOCE (vocab Pro temático)
        { id:'s8_con_f1', container:'conoce', tier:'facil', type:'matching',
          q:'Match each word with its meaning:',
          pairs:[{left:'bill',right:'Proyecto de ley'},{left:'recession',right:'Recesión'},{left:'hypothesis',right:'Hipótesis'},{left:'ruling',right:'Fallo judicial'}],
          distractors:['Receta','Paraguas'] },
        { id:'s8_con_f2', container:'conoce', tier:'facil', type:'oddOneOut',
          q:'Which word is NOT about politics or law?', options:['legislation','election','policy','recipe'], answer:'recipe' },
        { id:'s8_con_m1', container:'conoce', tier:'media', type:'multipleChoice',
          q:'A period when the economy shrinks and people lose jobs. What is it?', options:['recession','promotion','breakthrough','audience'], answer:'recession' },
        { id:'s8_con_m2', container:'conoce', tier:'media', type:'fillBlank',
          q:'Scientists tested their ___ in the lab for years.', hint:'idea científica que se quiere probar', answer:'hypothesis' },
        { id:'s8_con_d1', container:'conoce', tier:'dificil', type:'categorySort',
          q:'Sort each word by its field:',
          pool:['legislation','election','recession','inflation','hypothesis','experiment'],
          buckets:[{label:'Política / Leyes',correct:['legislation','election']},{label:'Economía',correct:['recession','inflation']},{label:'Ciencia',correct:['hypothesis','experiment']}] },
        { id:'s8_con_d2', container:'conoce', tier:'dificil', type:'audioQuestion',
          audioText:'By the time the new law passed, the economy had already entered a recession.',
          q:'What had happened before the law passed?',
          options:['La economía ya estaba en recesión','La economía mejoró','No pasó nada','La bolsa subió'], answer:'La economía ya estaba en recesión' },
        // ENTIENDE (perfects + conditionals)
        { id:'s8_ent_f1', container:'entiende', tier:'facil', type:'multipleChoice',
          q:'The government ___ passed three new laws this year.', options:['has','have','had','did'], answer:'has' },
        { id:'s8_ent_f2', container:'entiende', tier:'facil', type:'trueFalse',
          q:'The third conditional talks about imaginary situations in the PAST.', answer:true },
        { id:'s8_ent_m1', container:'entiende', tier:'media', type:'audioQuestion',
          audioText:'If I had invested earlier, I would be rich now.', q:'Did the person invest early?',
          options:['No','Sí','Tal vez','El año pasado'], answer:'No' },
        { id:'s8_ent_m2', container:'entiende', tier:'media', type:'matching',
          q:'Match each structure with its description:',
          pairs:[{left:'Present Perfect',right:'have + participio (hasta ahora)'},{left:'Past Perfect',right:'had + participio (antes de otro pasado)'},{left:'Third Conditional',right:'If had + part., would have + part.'}],
          distractors:['be + participio (pasiva)','present continuous'] },
        { id:'s8_ent_d1', container:'entiende', tier:'dificil', type:'dialogueFill',
          q:'Choose the most natural response for B:',
          dialogue:[{speaker:'A',line:'Why are you so broke?'},{speaker:'B',line:null},{speaker:'A',line:'Ouch, hindsight is painful.'}],
          options:["If I had saved, I wouldn't be broke now.","If I save, I wouldn't be broke.","If I would save, I wouldn't be broke.","If I saved, I won't be broke."],
          answer:"If I had saved, I wouldn't be broke now." },
        { id:'s8_ent_d2', container:'entiende', tier:'dificil', type:'multipleChoice',
          q:'"They have reformed the policy, but the damage had already been done." Which happened FIRST?',
          options:['The damage','The reform','Both at once','Neither'], answer:'The damage' },
        // PRODUCE
        { id:'s8_pro_f1', container:'produce', tier:'facil', type:'fillBlank',
          q:'Parliament ___ (vote) on the bill three times this month.', hint:'present perfect: has + participio', answer:'has voted' },
        { id:'s8_pro_f2', container:'produce', tier:'facil', type:'unscramble',
          spanishPrompt:'Ella ya se había ido cuando llegué.', targetLabel:'Arma la AFIRMACIÓN (+)',
          words:['She','had','already','left','when','I','arrived','has','did'],
          answer:'She had already left when I arrived', acceptedAnswers:['she had already left when i arrived'] },
        { id:'s8_pro_m1', container:'produce', tier:'media', type:'fillBlank',
          q:'If he ___ (invest) in stocks, he would have made a profit.', hint:'if + had + participio', answer:'had invested' },
        { id:'s8_pro_m2', container:'produce', tier:'media', type:'unscramble',
          spanishPrompt:'Deberías haberme dicho.', targetLabel:'Arma la oración (should have)',
          words:['You','should','have','told','me','of','had'],
          answer:'You should have told me', acceptedAnswers:['you should have told me'] },
        { id:'s8_pro_d1', container:'produce', tier:'dificil', type:'translate',
          spanishPrompt:'Vi al ministro ayer.', answer:'I saw the minister yesterday.', acceptedAnswers:['i saw the minister yesterday'] },
        { id:'s8_pro_d2', container:'produce', tier:'dificil', type:'multipleResponse',
          q:'Select ALL the grammatically correct sentences.',
          options:['You should have called.','You should of called.','If I had known, I would have sold.','If I would have known, I would have sold.'],
          answers:['You should have called.','If I had known, I would have sold.'] },
      ] },
  ],
};
